[package]
name = "binary_macros"
version = "0.1.0"
authors = ["Pyry Kontio <pyry.kontio@drasa.eu>"]
description = "Macros for decoding binary-to-text encodings in string literals to [u8] literals."
license = "MIT"

[dependencies]
data-encoding = "1.1.2"

[dev-dependencies]
dotenv = "0.8"
dotenv_macros = "0.9"

[lib]
plugin = true
